version: '3.8'
services:
  php-apache-mysql-environment:
    container_name: php-apache-mod
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 'Relational@Palace100'
        MYSQL_DATABASE: 'BLOG'
        MYSQL_USER: 'aakash_explorer'
        MYSQL_PASSWORD: 'aakash_explorer'
    ports:
        - "9907:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:80'
    restart: always
    environment:
        PMA_HOST: mysql_db
    depends_on:
        - mysql_db
  